---

- name: Get Cloudera Manager API version
  uri:
    url: https://{{ hostvars[scm_hostname]['inventory_hostname'] }}:{{ scm_port_https }}/api/version
    method: GET
    status_code: 200
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    force_basic_auth: yes
    return_content: yes
    validate_certs: no
  register: result

# Set base CM API URL
- set_fact:
    cm_api_url_https: "https://{{ hostvars[scm_hostname]['inventory_hostname'] }}:{{ scm_port_https }}/api/{{ result.content }}"

- debug:
    var: cm_api_url_https
    verbosity: 0

- name: deploy client configs
  uri:
    url: "{{ cm_api_url_https }}/clusters/{{ cluster_display_name }}/commands/deployClientConfig"
    method: POST
    status_code: 200
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
    validate_certs: no
    body_format: json
  register: start_resp5

- debug:
    var: start_resp5
    verbosity: 0

- name: Restart Cloudera Management Service
  uri:
    url: "{{ cm_api_url_https }}/cm/service/commands/restart"
    method: POST
    status_code: 200
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
    validate_certs: no
  register: start_resp3


- name: Sleep for 60 seconds and continue with play
  wait_for:
    timeout: 60

- name: Restart  regular Services
  uri:
    url: "{{ cm_api_url_https }}/clusters/{{ cluster_display_name }}/commands/restart"
    method: POST
    status_code: 200
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
    validate_certs: no
    body_format: json
  register: start_resp4

- debug:
    var: start_resp4
    verbosity: 0

- set_fact:
    command_id_ssvc: "{{ start_resp4.json.id }}"

- debug:
    msg: "Login to Cloudera Manager to monitor start progress - http://{{ hostvars[scm_hostname]['inventory_hostname'] }}:{{ scm_port }}/cmf/command/{{ command_id_ssvc }}/details"
    verbosity: 0

- name: Wait for start command to complete
  uri:
    url: "{{ cm_api_url_https }}/commands/{{ command_id_ssvc }}"
    body_format: json
    force_basic_auth: yes
    user: "{{ scm_default_user }}"
    password: "{{ scm_default_pass }}"
    return_content: yes
    validate_certs: no
    body_format: json
  register: result_ssvc
  until: not result_ssvc.json.active
  retries: 100
  delay: 60
  failed_when: "'Failed to start mgt' in result_ssvc.content"

- debug:
    var: result_ssvc
    verbosity: 0
